- README.md
- docs/SECURITY.md
- Created SECURITY.md to provide information on security practices and vulnerability reporting.
- Updated README.md to include a section with a link to the security policy for easy access.
> docs: Add SECURITY.md and update README with link to security policy

- server/controllers/userController.js
- server/models/userModel.js
- server/package.json
- server/routes/userRoutes.js
- server/server.js
- server/validation/userValidation.js
- Created the POST /api/users/signup route to allow visitors to register on the HappiHub platform.
- Added user validation using Joi.
- Implemented password hashing with bcrypt.
- Added JWT token generation for user authentication upon successful registration.
- Integrated the user model with Mongoose.
- Configured the necessary routes and controllers for the signup functionality.
> feat: Implement user signup route

- README.md
- docs/FAQ.md
- Created FAQ.md to provide answers to frequently asked questions about HappiHub.
- Updated README.md to include a section linking to the FAQ for easy access.
> docs: Add FAQ.md and update README with link to FAQ

- README.md
- docs/API_DOCUMENTATION.md
- Added API_DOCUMENTATION.md in the docs/API/ directory with detailed descriptions of API endpoints, parameters, and examples.
- Updated README.md to include a section linking to the API documentation and explaining its contents.
> docs: Create API_DOCUMENTATION.md and update README.md

- README.md
- docs/changelog/CHANGELOG.md
- docs/changelog/CHANGELOG_GUIDE.md
- Created CHANGELOG.md to document the changes, additions, bug fixes, and improvements in the project.
- Created CHANGELOG_GUIDE.md to provide instructions on how, when, and why to update the CHANGELOG.md.
- Updated README.md to include information about the CHANGELOG and how to use it.
See CHANGELOG_GUIDE.md for detailed instructions on maintaining the CHANGELOG.
> docs: Add CHANGELOG.md, CHANGELOG_GUIDE.md and update README.md

- package-lock.json
- package.json
- server/controllers/userController.js
- server/models/userModel.js
- server/package.json
- server/routes/userRoutes.js
- server/server.js
- server/validation/userValidation.js
- Created the POST /api/users/login route in the user controller.
- Added validation for login data.
- Implemented user authentication.
- Generated JWT token for authenticated users.
- Returned appropriate response after login.
- Updated .env file to include JWT_SECRET and JWT_EXPIRATION variables.
- Ensured that all necessary dependencies (jsonwebtoken) are installed.
Ref: feature/user-login
> feat: Implement user login route

- README.md
- server/controllers/userController.js
- server/middleware/auth.js
- server/package-lock.json
- server/package.json
- server/utils/jwt.js
- Installed jsonwebtoken and dotenv dependencies
- Created utility function for generating JWT tokens
- Updated signup route to generate and return JWT token
- Updated login route to generate and return JWT token
- Created middleware for verifying JWT tokens
- Documented JWT authentication usage in README.md
> feat: Implement JWT authentication for user signup and login

- server/controllers/eventController.js
- server/models/eventModel.js
- server/routes/eventRoutes.js
- server/server.js
- server/validation/eventValidation.js
- Add createEvent controller in eventController.js
- Create POST /api/events route in eventRoutes.js with authentication
- Update server.js to include event routes
This implementation allows authenticated users to create new events on the HappiHub platform.
> feat(events): add route to create new events

- server/controllers/eventController.js
- server/routes/eventRoutes.js
- Implemented GET /api/events route in eventController.js
- Added eventRoutes.js to handle the events routes
- Updated server.js to use eventRoutes
- Added Event model in models/Event.js
> feat(events): create route to get all events

- .gitignore
- docs/GUIDE.md
- server/controllers/userController.js
- server/models/eventModel.js
- server/models/userModel.js
- server/routes/userRoutes.js
- server/validation/userValidation.js
This pull request introduces the concept of "rank" to the user profiles on the HappiHub platform. The rank allows users to have a hierarchical status within the platform, enhancing the user experience and enabling new features based on user rank.
- Added a `rank` field to the `userSchema` in `userModels.js`.
- Updated the `userController.js` to handle the rank in profile updates.
- Modified the `userRoutes.js` to accommodate the rank during user updates.
- Updated the `GUIDE.md` to document the new rank feature and how it is used within the platform.
1. **Update User Profile with Rank:**
- Use Postman or a similar tool to send a PUT request to `/api/users/profile` with a valid `rank` field in the request body.
- Ensure the user profile is updated correctly and the rank is saved in the …
> Add Rank to User Profile

- docs/API_DOCUMENTATION.md
- server/.env
- server/controllers/eventController.js
- server/controllers/userController.js
- server/middleware/auth.js
- server/routes/eventRoutes.js
- server/routes/userRoutes.js
- Add getUserRole function in userController.js to retrieve the current user role
- Add GET /role route in userRoutes.js
- Add comments in auth.js
- Update API documentation in API_DOCUMENTATION.md to include new routes
- Add getAllPublicEvents function in eventController.js
- Add GET /events/public route in eventRoutes.js
> feat(users): implement GET /api/users/role route

- server/controllers/commentController.js
- server/controllers/eventController.js
- server/controllers/userController.js
- server/models/commentModel.js
- server/routes/commentRoutes.js
- server/server.js
- server/validation/commentValidation.js
- server/validation/eventValidation.js
- server/validation/userValidation.js
**Description:**
This pull request implements a new route `POST /api/comments/add` allowing authenticated users to leave a comment on a specific event. This feature is crucial to promote engagement and community interaction on the HappiHub platform.
**Changes:**
1. **Addition of the Comment Route:**
- Created `commentRoutes.js` to handle comment-related routes.
- Added the `POST /api/comments/add` route in `commentRoutes.js`.
2. **Comment Controller:**
- Created `commentController.js`.
- Implemented the `addComment` function to handle the logic for adding a comment.
3. **ID Validation:**
- Added `isValidUserId` function to `userValidation.js`.
- Added `isValidEventId` function to `eventValidation.js`.
- Utilized validation functions to check `user_id` and `event_id` before adding a …
> Implement POST `/api/comments/add` Route

- server/controllers/userController.js
- server/middleware/auth.js
- server/utils/hashPassword.js
- server/utils/jwt.js
**Description:**
This pull request implements password hashing for user passwords before storing them in the database, thereby enhancing application security.
**Proposed Changes:**
- Implemented bcrypt library for password hashing.
- Updated user model and controllers to hash passwords before saving.
- Ensured existing users' passwords are securely hashed upon update or login.
**Resolved Issue:**
Closes #135
Please review and merge this pull request. Thank you!
>  Implement Password Hashing for User Security

- README.md
- docs/jwt/JWT_DOCUMENTATION.md
This pull request introduces detailed documentation on managing JWT tokens within the HappiHub project. The new documentation provides comprehensive guidelines and examples on how to generate, validate, and refresh JWT tokens, as well as security best practices for token management.
- Added introduction to JWT and its usage in HappiHub
- Included detailed steps for generating JWT tokens with code examples
- Added methods for validating JWT tokens with code examples
- Included procedures for refreshing JWT tokens with code examples
- Added a section on security best practices for managing JWT tokens
- Integrated the document into the `docs` folder
- Updated the `README.md` file to include a link to the new documentation
Proper management of JWT tokens is crucial for the security and …
> Add Comprehensive JWT Token Management Documentation

- server/controllers/commentController.js
- server/controllers/userController.js
- server/models/commentModel.js
- server/routes/commentRoutes.js
- server/server.js
- Updated the comment model to include `content`, `author`, `event`, and `status` fields.
- Modified the comment creation controller to handle the new fields and set `status` to `pending` by default.
- Tested the comment creation with Postman to ensure proper functionality.
> feat: add comment creation route with status, author, and event fields

- server/controllers/commentController.js
- server/models/commentModel.js
- server/routes/commentRoutes.js
This pull request implements the `PUT /comments/:id` route to update a specific comment by ID and includes author verification to ensure that only the author of the comment or an admin/moderator can update the comment.
- Added `updateCommentById` method to `commentController` to handle updating a specific comment by ID.
- Created a new route in `commentRoutes.js` for `PUT /comments/:id`, protected by `authenticateToken` middleware.
- Implemented error handling to return `404 Not Found` if the comment is not found.
- Added verification to ensure only the author of the comment or an admin/moderator can update the comment.
- Implemented error handling to return `403 Forbidden` if the user does not have permission.
- Verified functionality with Postman tests.
1. **Update Comment as Author**: …
> feat: implement PUT /comments/:id route with author verification

- server/controllers/commentController.js
- server/controllers/userController.js
- server/middleware/auth.js
- server/routes/commentRoutes.js
- server/validation/userValidation.js
This pull request implements the `GET /comments` route that allows administrators to retrieve all comments. This route is secured and accessible only to users with admin privileges.
- Created `getAllComments` method in `commentController` to handle retrieving all comments.
- Added authentication middleware (`authenticateToken`) to protect the route.
- Added authorization middleware (`isAdmin`) to ensure only admins can access this route.
- Verified functionality with Postman tests using both admin and non-admin accounts.
1. **Retrieve All Comments as Admin**:
- Send a `GET` request to `http://localhost:5000/api/comments` with a valid admin token in the `Authorization` header.
- Ensure the response includes all comments.
2. **Unauthorized Access Attempt**:
- Send a `GET` request to …
> feat: implement GET /comments route for admins to retrieve all comments

- server/controllers/commentController.js
- server/middleware/auth.js
- server/models/commentModel.js
- server/routes/commentRoutes.js
This pull request implements the `DELETE /comments/:id` route that allows authenticated users to delete a specific comment by its ID. The route ensures that only the author of the comment or an admin can perform the deletion.
- Added `deleteCommentById` method to `commentController` to handle deleting a comment.
- Created a new route in `commentRoutes.js` for `DELETE /comments/:id`, protected by `authenticateToken`.
- Added verification to ensure only the author of the comment or an admin can delete the comment.
- Implemented error handling to return `404 Not Found` if the comment is not found.
- Verified functionality with Postman tests.
1. **Delete Comment as Author**:
- Send a `DELETE` request to `http://localhost:5000/comments/:id` with a valid comment ID where the author matches the …
> `feature/delete-comment-by-id`

- docs/CONTRIBUTING.md
This Pull Request updates the `CONTRIBUTING.md` file to include the latest branch, commit, and pull request naming conventions. This update provides clear guidelines for naming branches, commits, and pull requests to ensure consistency and improve collaboration within the project.
- Closes #32
- Added detailed structure for commit messages.
- Defined a comprehensive format for branch naming.
- Established guidelines for pull request naming and description.
> docs: update CONTRIBUTING.md with new naming conventions

- docs/joi-validation-guide.md
This pull request finalizes the implementation of the comprehensive documentation for Joi validation in the HappiHub project. It addresses the requirements outlined in Issue #211.
- Added comprehensive sections covering the introduction, setup, and basic concepts of Joi.
- Detailed guides for creating and validating schemas for various data types.
- Advanced validation techniques including nested objects, arrays, and conditional logic.
- Custom error messages, localization, and handling multiple errors.
- Options for global and schema-specific validation configurations.
- Asynchronous validation with examples using promises.
- Integration of Joi with Express.js, Hapi.js, and Koa.js frameworks.
- Common use cases such as login and registration form validation.
- Debugging and …
> `docs/211-joi-validation-documentation`

- docs/express/GUIDE_EXPRESS.md
This pull request adds a comprehensive guide for the Express framework documentation to the HappiHub project. The documentation includes detailed sections on installation, configuration, basic concepts, advanced features, best practices, complete application examples, and additional resources.
The new documentation aims to provide a consistent and detailed reference for developers using Express in the HappiHub project. It covers essential topics to help maintain best practices and streamline the development process.
- Added detailed sections on the following:
- Installation and configuration
- Basic concepts (routes, middlewares, views)
- Advanced features (error handling, security, authentication)
- Best practices (code organization, testing, documentation)
- Complete application …
> feat(docs): add comprehensive Express documentation guide

- client/src/App.js
- client/src/components/Card/card.css
- client/src/components/Comment/Comment.jsx
- client/src/components/Comment/comment.css
- client/src/components/Event/EventInfo.jsx
- client/src/components/Event/event.css
- client/src/components/Header/Header.jsx
- client/src/components/Header/header.css
- client/src/components/Home/Home.jsx
CHECK IT GUYS BECAUSE THIS FUCKING COMMENT SECTION DOESNT MOVE YYYYYYYYYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
SIL VOUS PLAIT
> BUKKAKKKEEEE
